#
# Copyright (c) 2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

model:
  name: inception_v3
  framework: tensorflow

pruning:
  train:
    dataloader:
      batch_size: 128
      dataset:
        ImageRecord:
          root: /path/to/training/dataset             # NOTE: modify to the ImageNet training set location
      transform:
        BilinearImagenet: 
          height: 299
          width: 299
    postprocess:
      transform:
        LabelShift: 1
    epoch: 40
    optimizer:
      Adam:
        learning_rate: 1e-06
        beta_1: 0.9
        beta_2: 0.999
        epsilon: 1e-07
        amsgrad: False
    criterion:
      SparseCategoricalCrossentropy:
        reduction: sum_over_batch_size
        from_logits: False
  approach:
    weight_compression:
      initial_sparsity: 0.0
      target_sparsity: 0.54
      start_epoch: 0
      end_epoch: 19
      pruners:
        - !Pruner
            start_epoch: 0
            end_epoch: 19
            prune_type: basic_magnitude

evaluation:                                         # optional. required if user doesn't provide eval_func in neural_compressor.Quantization.
  accuracy:                                         # optional. required if user doesn't provide eval_func in neural_compressor.Quantization.
    metric:
      topk: 1                                       # built-in metrics are topk, map, f1, allow user to register new metric.
    dataloader:
      distributed: False
      batch_size: 512
      dataset:
        ImageRecord:
          root: /path/to/validation/dataset         # NOTE: modify to the ImageNet validation set location
      transform:
        BilinearImagenet: 
          height: 299
          width: 299
    postprocess:
      transform:
        LabelShift: 1

tuning:
  accuracy_criterion:
    relative: 0.01                                  # the tuning target of accuracy loss percentage: 1%
  exit_policy:
    timeout: 0                                      # tuning timeout (seconds)
  random_seed: 9527                                 # random seed
